### DISCUSSION TITLE
How can I add custom routes to traefik?

### DISCUSSION THREAD

**Discussion by WinstonN** [wardenenv/warden#563] [Help & Support]
When I use NGROK, or localtunnel, to create a tunnel between my docker environment, and the internet, I always get a 404 page

This page seems to belong to traefik
I get the same page when I hit https://localhost:443

I want to ensure that when I use a service like localtunnel, and I set the local-host to the same as my local site, that I reach it and not a 404

an example command below
```bash
lt --local-host mysite.test --subdomain mysite --port 443
```

**Comment by davidalger** [comment]
@WinstonN The info here should be of help on this front: https://docs.warden.dev/configuration/multipledomains.html

**Comment by WinstonN** [comment]
@davidalger I have used that document, and have a setup like this currently

.warden/warden-env.yml
```yaml
version: "3.5"
services:
    nginx:
        labels:
            - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=
                HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
                || Host(`${TRAEFIK_DOMAIN}`)
                || HostRegexp(`{subdomain:.+}.localhost`)
                || Host(`localhost`)
                || HostRegexp(`{subdomain:.+}.localhost.test`)
                || Host(`localhost.test`)
                || HostRegexp(`testsubdomain.loca.lt`)
                || Host(`testsubdomain.loca.lt`)
                || HostRegexp(`127.0.0.1`)
                || Host(`127.0.0.1`)
    php-fpm:
        extra_hosts:
            - localhost:${TRAEFIK_ADDRESS:-0.0.0.0}
            - localhost.test:${TRAEFIK_ADDRESS:-0.0.0.0}
            - testsubdomain.loca.lt:${TRAEFIK_ADDRESS:-0.0.0.0}
            - 127.0.0.1:${TRAEFIK_ADDRESS:-0.0.0.0}
    php-debug:
        extra_hosts:
            - localhost:${TRAEFIK_ADDRESS:-0.0.0.0}
            - localhost.test:${TRAEFIK_ADDRESS:-0.0.0.0}
            - testsubdomain.loca.lt:${TRAEFIK_ADDRESS:-0.0.0.0}
            - 127.0.0.1:${TRAEFIK_ADDRESS:-0.0.0.0}
```

When I open up 
- localhost
- localhost.test
- 127.0.0.1

My development site loads correctly

The problem I have is, using NGROK, or something like localtunnel, I always get a 404 - see image

How can I log that 404 page? It seems like it's a traefik/nginx page
The issue seems to be, DNS related? 

![image](https://user-images.githubusercontent.com/1143789/112070541-c33ed500-8bd2-11eb-9ff4-58db23ec7ee1.png)
