### DISCUSSION TITLE
Easier way to connect environments

### DISCUSSION THREAD

**Discussion by navarr** [wardenenv/warden#650] [Ideas]
Right now, the steps for connecting environments together involve:

Ex: app.a.test <-> app.b.test

* `warden shell` into a.test
  * ping a.test record IP (<a.test ip>)
* `warden shell` into b.test
  * ping b.test record IP (<b.test ip>)
* Edit `warden-env.yml` for a.test, under the image you want to be able to connect to b.test:  
  ```yaml
  extra_hosts:
    - app.a.test:<a.test ip>
  ```
* Edit `warden-env.yml` for b.test, under the image you want to be able to connect to a.test:
  ```yaml
  extra_hosts:
   - app.b.test:<b.test ip>
  ```
 * `warden env up` both environments
 * `docker network connect a_default <image for b, e.g. b-php-fpm-1>`
 * `docker network connect b_default <image for a, e.g. a-php-fpm-1>`

Ideally, this should be something like a `CONNECTED_PROJECT=` variable in `.env` that takes care of all the steps.

**Comment by tdgroot** [comment]
Haven't done this in a while, but I used to generate a file like this:

```yml
version: 3.5
services:
  php-fpm:
    extra_hosts:
      - app.b.test:${TRAEFIK_ADDRESS:-0.0.0.0}
  php-debug:
    extra_hosts:
      - app.b.test:${TRAEFIK_ADDRESS:-0.0.0.0}
```

This made it possible to make requests from one environment to another.
