### DISCUSSION TITLE
How to configure Multisite using subdirectories in Wordpress on Warden

### DISCUSSION THREAD

**Discussion by KarthikMadathil** [wardenenv/warden#680] [Help & Support] [answered]
Does anybody know how to configure WordPress multisite

**Comment by KarthikMadathil** [comment, marked as answer]
First create .warden/warden-env.yml file

Add below configuration for altering Nginx configuration

```
version: "3.5"
services:
  nginx:
    volumes:
      - ./.warden/nginx/custom.conf:/etc/nginx/default.d/custom.conf

```

now create  .warden/nginx/custom.conf

Add below configuration 


```
if (!-e $request_filename) {
  rewrite /wp-admin$ $scheme://$host$uri/ permanent;
  rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
  rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
}
      
```


Now Follow the steps for setting up multisite configuration in WordPress 
like 
Altering  wp-config.php
and so on ..

Cheers
