### DISCUSSION TITLE
PR for linux permissions

### DISCUSSION THREAD

**Discussion by toonvd** [wardenenv/warden#696] [Ideas]
Hi @navarr and @davidalger 

I am willing to PR on this but wanted to discuss implementation.

Steps:

- Get host uid and host gid and add them as env var:
   ```bash
   #!/bin/bash

  export HOSTUID=$(id -u)
  export HOSTGID=$(id -g)
  ```
  Probably here: https://github.com/wardenenv/warden/blob/main/commands/env.cmd#L147
- Add host uid and host gid as args to containers and make them the default user:
  ```yaml
    args:
        HOSTUID: ${HOSTUID}
        HOSTGID: ${HOSTGID}
    user: "${HOSTUID}:${HOSTGID}"
  ```
- Add the args to the Dockerfiles and add a "warden" user on those ids:
  ```bash
  ARG HOSTGID
  ARG HOSTUID
  RUN groupadd -g $HOSTGID -o warden
  RUN useradd -m -u $HOSTUID -g $HOSTGID -o -s /bin/bash warden
  ```
