### DISCUSSION TITLE
Requestbasket

### DISCUSSION THREAD

**Discussion by toonvd** [wardenenv/warden#737] [Ideas]
Hi

Would you accept a PR to add requestbasket to the default services?
I use it to debug webhooks a lot and implemented it in our companies' Warden.

![reqbasket](https://github.com/wardenenv/warden/assets/1227745/97bbe333-4753-41a2-a7bc-021a261a7621)

**Comment by bap14** [comment]
While I'm not opposed to adding a new tools, I do worry about "bloat" when we have a simple way to extend warden for your own environments and installations already. You could add this to your local `~/.warden/docker-compose.yml` file and have it running like any other global service each time you start Warden.

```yaml
version: "3.5"
services:
  requestbasket:
    container_name: requestbasket
    image: darklynx/request-baskets
    labels:
      - traefik.enable=true
      - traefik.http.routers.requestbasket.tls=true
      - traefik.http.routers.requestbasket.rule=Host(`requestbasket.${WARDEN_SERVICE_DOMAIN:-den.test}`)||Host(`requestbasket.warden.test`)
      - traefik.http.services.requestbasket.loadbalancer.server.port=55555
```
