### DISCUSSION TITLE
Communication between warden environments

### DISCUSSION THREAD

**Discussion by cjnewbs** [wardenenv/warden#778] [Help & Support] [answered]
I have been looking at [this](https://github.com/orgs/wardenenv/discussions/777) to try fix my issue but I don't seem to quite be able to resolve it.

I have 2 warden environments:
- Laravel (laravel.test)
- Magento 2 (magento.test)

I need to make API calls into Magento from Laravel.

My Magento `.warden/warden-env.yml` file looked like this:
```
version: "3.5"
services:
  php-fpm:
    networks:
      - laravel_default
      - magento_default
    extra_hosts:
      - "laravel.test:laravel-nginx-1"
networks:
  laravel_default:
    external: true
  magento_default:
    external: true
```

My Laravel `.warden/warden-env.yml` file looked like this:
```
version: "3.5"
services:
  mongo-db:
    image: 'mongo:4.0.25'
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  php-fpm:
    networks:
      - laravel_default
      - magento_default
    extra_hosts:
      - "magento.test:magento-varnish-1"

networks:
  laravel_default:
    external: true
  magento_default:
    external: true
```

Running `docker network inspect {magento|laravel}_default` shows that the `php-fpm` container has been attached to the network.

However running `curl magento.test -vvv` outputs:
```
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to magento.test port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to magento.test port 80: Connection refused
```

As I understand (possibly incorrectly) the `extra_hosts` node should add to the `/etc/hosts` a new entry that maps `magento.test` to the IP address that is attached to the `magento-varnish-1` container.

I have made dozens of changes to both files. I realised I only needed to make requests from Laravel -> Magento so stopped trying to make the config yaml files match as thats probably over-complicating it by enabling both projects. Ive now been working on `laravel/.warden/warden-env.yml` for about 3 hours with no luck.

I currently have just this for the laravel config and have removed the magento one:
```
version: "3.5"
services:
  mongo-db:
    image: 'mongo:4.0.25'
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  php-fpm:
    networks:
      - laravel_default
      - magento_default
    extra_hosts:
      - "magento.test:magento-varnish-1" # this entry currently gives the error `Error response from daemon: invalid IP address in add-host: "magento-varnish-1"
`

networks:
  laravel_default:
    external: true
  magento_default:
    external: true

```

Can anyone suggest where I am going wrong or point me in the right direction? Do I need to declare both networks in the laravel config or is this redundant? Am I going to have to resort to hard-coding the ip in extra_hosts for magento.test (that doesnt seem ideal, the ip can change right?). My current config has got back to the point when i can access both from a browser (i have gone back-and-forth between that working and breaking)

**Comment by cjnewbs** [comment, marked as answer]
I figured it out. Warden already adds a hosts entry that routes to traefik to the php container (the one connected to with `warden shell`) so it was as simple as adding this into the `.warden/warden-env.yml` file of the project you wish to make HTTP requests from:
```
version: "3.5"
services:
  php-fpm:
    extra_hosts:
      - app.magento.test:${TRAEFIK_ADDRESS:-0.0.0.0}
  php-debug:
    extra_hosts:
      - app.magento.test:${TRAEFIK_ADDRESS:-0.0.0.0}
```
Just change `app.magento.test` to the project you wish to connect to.
