### DISCUSSION TITLE
How to access domain of one project from another project?

### DISCUSSION THREAD

**Discussion by rajeev-k-tomy** [wardenenv/warden#828] [Help & Support] [answered]
I have a Magento and a Laravel project setup and running. Both projects are up at the same time. I want to call Magento graphql request from laravel application. However, i get below error when i tried to do this

> cURL error 7: Failed to connect to magento.test port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://magento.test/graphql

Is there any way, i can achieve the same?

**Comment by dudzio12** [comment, marked as answer]
Fortunatelly you can do that, by creating `.warden/warden-env.yml` in projectA:

```
services:
  php-fpm:
    extra_hosts:
      - projectB.test:${TRAEFIK_ADDRESS:-0.0.0.0}

  php-debug:
    extra_hosts:
      - projectB.test:${TRAEFIK_ADDRESS:-0.0.0.0}
```

And accordingly for projectB.
