### DISCUSSION TITLE
How to make use of http://{ip-address}:{port} instead of https://{project}.test?

### DISCUSSION THREAD

**Discussion by MagePsycho** [wardenenv/warden#835] [Help & Support]
I have to use non-secure mode and IP for some of the use cases, for example: `http://{ip-address} :{port}`, for example: `http://192.168.216.10:2112`
How can I achieve this in Warden?
I tried changing the base URL and `web/secure/use_in_frontend|adminhtml` settings to `0`  but no luck.
It always redirects to the `https:` version.

Is there a way to make this happen in warden?

**Comment by MagePsycho** [comment]
@navarr I have a special requirement to setup Magento 2 using `http://<someIP>:<somePort>` 
Do you have any idea on how to do it so?

**Reply by bap14** [reply]
You could use ngrok as a public proxy to your Warden environment.

**Comment by hardyjohnson** [comment]
@MagePsycho I was interested to see if I could make that work.

There are a few different things you may need to work across to not be redirected (browser, traefik, nginx, magento).

To disable the global Traefik global http -> https redirect you can edit `~/.warden/etc/traefik/traefik.yml` and remove the entry point redirect (until #876 is fixed you will need to make this change in the warden install directory `<WARDEN_INSTALL_DIR>/config/traefik/traefik.yml`):

```
http:
      redirections:
        entryPoint:
          to: https
          scheme: https
```

You may also want to up the Traefik log level to debug in order to see requests coming into the Warden environment.
```
---
api:
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    network: warden
    defaultRule: "Host(`{{ .Name }}.warden.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
log:
  level: DEBUG
global:
  checkNewVersion: false
  sendAnonymousUsage: false
```
`warden svc restart` is required to enable that.

Note as host matching is used by Traefik to route the request to the proper service I am unsure if there is an easy way to use IP address directly. If you are unable to use the `dnsmasq` service, a local hosts file entry would work as well.

**Local Warden customization for the environment**

In the project level customization file: `<PROJECT_DIR>/.warden/warden-env.yml`

**After speaking with @MagePsycho I will clarify that the router name below must match your configured warden env name from your .env file. (WARDEN_ENV_NAME).**

```
services:
  nginx:
    labels:
      traefik.http.routers.<YOUR-ENV-NAME>-nginx.tls: "false"
```

**Magento application configuration**
- I set varnish to 0 in the project .env and reinstalled Magento.
- I set both the secure and unsecure URLs to http: and the use_in_ settings to 0 and flushed cache.

Depending on your browser you may need to turn off always HTTPS or similar settings in order to visit an http resource without https upgrade.

**Reply by hardyjohnson** [reply]
Note also this may break other local environments which expect the global redirect to be in effect so YMMV. Not sure if there is an easy project level method of manipulating the traefik.yml config, still looking at that. I tried a local traefik.yml file and using an -f or --env-file flag when starting / restarting the warden svc but that did not seem to get merged / work. Will report back if I do get that working.

**Reply by MagePsycho** [reply]
@hardyjohnson Thanks for stepping in.
First, lets try to make it work with `http:://{project}.test`.  I will go through you post meanwhile.
BTW, were you able to run without `https://`?

**Reply by hardyjohnson** [reply]
Yes I am able to run at plain http://{project}.test no https.

**Reply by MagePsycho** [reply]
Great. I will give it a try!

**Reply by MagePsycho** [reply]
@hardyjohnson I am giving it a try now.
Few questions:
```
log:
  level: DEBUG
```
What does it do exactly?

**Reply by MagePsycho** [reply]
@hardyjohnson I tried to setup but ending up with 404 after I loging to the admin.

http:://{project}.test/{store-code} for storefront -> 404
http:://{project}.test/backend/.. for admin -> 404

So far, what I have done is:
1. Edit file as you have described: ~/.warden/etc/traefik/traefik.yml followed by `warden svc restart`
1. set `WARDEN_VARNISH=0`  followed by `warden env up`
2. Edit the DB settings
```SET @BASE_URL = 'http://myproject.test/';
INSERT INTO core_config_data (scope, scope_id, path, value)
VALUES 
('default', 0, 'web/url/redirect_to_base', 0),
('default', 0, 'web/session/use_frontend_sid', 0),
('default', 0, 'web/unsecure/base_url', @BASE_URL),
('default', 0, 'web/secure/base_url', @BASE_URL),
('default', 0, 'web/secure/use_in_frontend', 0),
('default', 0, 'web/secure/use_in_adminhtml', 0)
ON DUPLICATE KEY UPDATE value = VALUES(value);
```

Let me know what am I missing?

**Reply by hardyjohnson** [reply]
I am running into a bug now, I probably had edited around it in the svc command and forgotten to open a bug, basically the traefik.yml will get overridden currently for every warden svc up 🤦🏽 . 

Cat your traefik.yml changes and see if they still exist: `cat ~/.warden/etc/traefik/traefik.yml`

https://github.com/wardenenv/warden/issues/876

**Reply by hardyjohnson** [reply]
OK, just looking at this again, it seems I missed a couple of items, I went back and edited the old response to include them. 

1. #876 
2. Need to turn off TLS for the Traefik Nginx label.

The Traefik service log level debug will show requests making it into the Warden svc and show headers for the requests like so:

```
2025 21:01:44 GMT\"],\"If-None-Match\":[\"\\\"6851d7b8-a\\\"\"],\"Priority\":[\"u=0, i\"],\"Sec-Gpc\":[\"1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:140.0) Gecko/20100101 Firefox/140.0\"],\"X-Forwarded-Host\":[\"app.warden-test-https.test\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"33c9a75aadfa\"],\"X-Real-Ip\":[\"172.23.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.warden-test-https.test\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.23.0.1:60422\",\"RequestURI\":\"/test2.txt\",\"TLS\":null}"
```

**Reply by MagePsycho** [reply]
@hardyjohnson In my case `cat ~/.warden/etc/traefik/traefik.yml` is not reset:
```
---
api:
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    network: warden
    defaultRule: "Host(`{{ .Name }}.warden.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https
  https:
    address: ":443"
log:
  level: DEBUG
global:
  checkNewVersion: false
  sendAnonymousUsage: false
```
Any page with `http://` results in 404.

How to debug the issue could be?

**Reply by MagePsycho** [reply]
@hardyjohnson What do you mean by this "Need to turn off TLS for the Traefik Nginx label."?

**Reply by hardyjohnson** [reply]
As per your comment, that is the bug #876, even if you modify the traefik.yml in your home warden directory it gets overwritten by the version in the warden install directory.

In order to solve the 404 issue I had to also turn off the Traefik setting which tries to make sure the router uses TLS by creating the following `./<PROJECT-DIR>/.warden/warden-env.yml`:

```
services:
  nginx:
    labels:
      traefik.http.routers.warden-test-https-nginx.tls: "false"
```

> How to debug the issue could be?

This is why changing the log level of Traefik is important because then you can see the requests in the Traefik container log.

**Reply by MagePsycho** [reply]
@hardyjohnson Sorry to bother you again.
I have this settings in `./<PROJECT-DIR>/.warden/warden-env.yml` followed by `warden env up` and cache refresh. Still facing the 404 page.
```
services:
  nginx:
    labels:
      traefik.http.routers.warden-test-https-nginx.tls: "false"
```

> This is why changing the log level of Traefik is important because then you can see the requests in the Traefik container log.

Do you know where to check those logs? 
I don't see any option in `https://traefik.warden.test/`
