### ISSUE TITLE
Postgress Support

### ISSUE THREAD

**Issue by emreakay** [wardenenv/warden#402]
Can you bring postgress support for laravel projects?

**Comment by tdgroot** [comment]
What do you mean exactly? Having a postgres database and the necessary PHP extension available?

**Comment by emreakay** [comment]
I mean can you add postgress as a new container like mysql

**Comment by tdgroot** [comment]
You could add a container like postgres to your development environment quite easily. It can be achieved by creating a file `.warden-env.yml` in the `.warden` directory of your development environment.

``` yaml
# .warden/warden-env.yaml
version: '3.5'
services:
  postgres:
    hostname: "${WARDEN_ENV_NAME}-postgres"
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  php-fpm:
    depends_on:
      postgres:
        condition: service_started
volumes:
  pgdata: {}
```

After creating the file, run `warden env up` and the following commands to install the postgresql client and postgres php extension:
```shell
warden env exec php-fpm sudo dnf install -y postgresql php-pgsql
warden env exec php-debug sudo dnf install -y postgresql php-pgsql
# for blackfire, if you use that
warden env exec php-blackfire sudo dnf install -y postgresql php-pgsql
```

Assuming you know how to connect to postgres, here are the credentials:
```
host: postgres
username: laravel
password: laravel
database: laravel
```

**Comment by emreakay** [comment]
hi @tdgroot 
filename must be warden-env.yml without dot.

Thanks

**Comment by tdgroot** [comment]
@emreakay Good catch! I corrected my comment.

**Comment by emreakay** [comment]
I have used this file,
It works correctly

`

# .warden/warden-env.yaml
version: '3.5'
services:
  postgres:
    hostname: "${WARDEN_ENV_NAME}-postgres"
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: laravel
      POSTGRES_USER: laravel
    volumes:
      - postgresdata:/var/lib/postgresql/data
  php-fpm:
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgresdata: {}
`

**Comment by WinstonN** [comment]
I have tried this config, but it does not work for me
My `.warden/warden-env.yaml` in the root of my project
```
# .warden/warden-env.yaml
version: '3.5'
services:
  postgres:
    container_name: ${WARDEN_ENV_NAME}-postgres
    hostname: ${WARDEN_ENV_NAME}-postgres
    image: postgres:13.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${WARDEN_ENV_TYPE}
      POSTGRES_USER: ${WARDEN_ENV_TYPE}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: ${WARDEN_RESTART_POLICY:-always}
  php-fpm:
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgresdata: {}
```

`warden env config` shows

```
win@laptop:~/Projects/project$ warden env config
networks:
  default:
    labels:
      dev.warden.environment.name: company-project
      dev.warden.environment.type: symfony
services:
  db:
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_USER: symfony
    hostname: companys-project-mariadb
    image: docker.io/wardenenv/mariadb:10.4
    volumes:
    - dbdata:/var/lib/mysql:rw
  nginx:
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      NGINX_PUBLIC: /public
      XDEBUG_CONNECT_BACK_HOST: host.docker.internal
    hostname: companys-project-nginx
    image: docker.io/wardenenv/nginx:1.16
    labels:
      traefik.enable: "true"
      traefik.http.routers.company-project-nginx.priority: '2'
      traefik.http.routers.company-project-nginx.rule: ' HostRegexp(`{subdomain:.+}.company-project.test`)
        || Host(`company-project.test`)'
      traefik.http.routers.company-project-nginx.tls: "true"
      traefik.http.services.company-project-nginx.loadbalancer.server.port: '80'
    volumes:
    - /home/win/Projects/project:/var/www/html:cached
  php-debug:
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      CHOWN_DIR_LIST: '/bash_history /home/www-data/.ssh '
      COMPOSER_MEMORY_LIMIT: '-1'
      COMPOSER_VERSION: '1'
      HISTFILE: /bash_history/.bash_history
      NODE_VERSION: '10'
      PHP_IDE_CONFIG: serverName=company-project-docker
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
      TRAEFIK_DOMAIN: company-project.test
      TRAEFIK_SUBDOMAIN: ''
    extra_hosts:
      company-project.test: 172.25.0.2
      app.company-project.test: 172.25.0.2
    hostname: company-project-php-debug
    image: docker.io/wardenenv/php-fpm:7.0-debug
    volumes:
    - bashhistory:/bash_history:rw
    - /home/win/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
    - /home/win/.composer:/home/www-data/.composer:cached
    - sshdirectory:/home/www-data/.ssh:rw
    - /dev/null:/run/host-services/ssh-auth.sock:rw
    - /home/win/Projects/project:/var/www/html:cached
  php-fpm:
    depends_on:
      db:
        condition: service_started
    environment:
      CHOWN_DIR_LIST: '/bash_history /home/www-data/.ssh '
      COMPOSER_MEMORY_LIMIT: '-1'
      COMPOSER_VERSION: '1'
      HISTFILE: /bash_history/.bash_history
      NODE_VERSION: '10'
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
      TRAEFIK_DOMAIN: company-project.test
      TRAEFIK_SUBDOMAIN: ''
    extra_hosts:
      company-project.test: 172.25.0.2
      app.company-project.test: 172.25.0.2
    hostname: company-project-php-fpm
    image: docker.io/wardenenv/php-fpm:7.0
    volumes:
    - bashhistory:/bash_history:rw
    - /home/win/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
    - /home/win/.composer:/home/www-data/.composer:cached
    - sshdirectory:/home/www-data/.ssh:rw
    - /dev/null:/run/host-services/ssh-auth.sock:rw
    - /home/win/Projects/project:/var/www/html:cached
  redis:
    hostname: company-project-redis
    image: docker.io/wardenenv/redis:5.0
    volumes:
    - redis:/data:rw
version: '3.5'
volumes:
  bashhistory: {}
  dbdata: {}
  redis: {}
  sshdirectory: {}

```

It's asif the new config is ignored
I have tried on v0.11.0 and 0.12.0

Do you know what I am doing wrong here?

I am running this setup on 
Windows 10 with wsl2 
Docker version 20.10.12, build e91ed57
