### ISSUE TITLE
php 8.2 support

### ISSUE THREAD

**Issue by emreakay** [wardenenv/warden#559]
hi,

when will you bring php 8.2 support

thanks.

**Comment by navarr** [comment]
We do not currently have an estimated timeline for PHP 8.1 and 8.2 support.

If these are critical, you may want to use the [Den](https://github.com/swiftotter/den) fork in the interim.

**Comment by navarr** [comment]
You can now use 8.2 Warden images by customizing your `.warden/warden-env.yml` file.

```
version: "3.5"
services:
  php-fpm:
    image: ghcr.io/wardenenv/php-fpm:${PHP_VERSION:-7.4}{$WARDEN_SVC_PHP_VARIANT:-}
  php-debug:
    image: ghcr.io/wardenenv/php-fpm:${PHP_VERSION:-7.4}{$WARDEN_SVC_PHP_VARIANT:-}
```
