### ISSUE TITLE
[Command] warden env start

### ISSUE THREAD

**Issue by pczerkas** [wardenenv/warden#739]
### Version of Warden

in-dev (commit 6f650ec7c31beff65fdff2f3202e242014c8a9dc)

### Operating System and Installation Method

Ubuntu 20.04.6 LTS, docker ce 25.0.0, installed using "Alternative Installation" from https://docs.warden.dev/installing.html#alternative-installation

### Describe the Bug

Started to happen on docker ce version 25.0.0:

```
$ warden env start
validating /opt/warden/environments/includes/varnish.base.yml: services.nginx.labels array items[2,7] must be unique
```

what helps is to downgrade `docker-compose-plugin` from version `2.24.1-1~ubuntu.20.04~focal` to version `2.21.0-1~ubuntu.20.04~focal` (or downgrade whole docker from `25.0.0` to `24.0.7`)

**Comment by mattijv** [comment]
Some more info in https://github.com/wardenenv/warden/issues/740

**Comment by pczerkas** [comment]
https://github.com/moby/moby/issues/47122
https://github.com/docker/compose/issues/11371

**Comment by mattijv** [comment]
So if I interpret the issues linked by @pczerkas correctly, this problem should be fixed in the next version of `docker compose` is released, and is not an issue with Warden at all.

**Comment by mattijv** [comment]
BTW commenting out the last two labels in the `varnish.base.yml` service definition is an effective workaround if you do not feel like downgrading `docker compose`.

**Comment by iranimij** [comment]
> BTW commenting out the last two labels in the `varnish.base.yml` service definition is an effective workaround if you do not feel like downgrading `docker compose`.

It didn't work for me

**Comment by iranimij** [comment]
I removed the whole file (/home/linuxbrew/.linuxbrew/Cellar/warden/0.14.1/environments/includes/varnish.base.yml) and it worked

**Comment by mattijv** [comment]
Removing the file is certainly effective, but personally I'd maybe not recommend it, as it will probably break other things.

[Looks like](https://github.com/docker/compose/releases/tag/v2.24.4) the issue will be fixed in the latest version of docker compose (v2.24.4). (Did not test, as that version does not yet seem to be available in the `apt` repo.)

**Comment by ihor-sviziev** [comment]
I can confirm that after manual upgrade docker-compose-plugin to 2.24.4, the issue is gone.
However, for those who use Docker Desktop for Mac, it's automatically replaces the docker compose plugin when you restarting it, which isn't good.
The workaround for Mac is downgrading Docker Desktop to version [4.26.1](https://docs.docker.com/desktop/release-notes/#4261)

**Comment by SamJUK** [comment]
Work around for ubuntu while apt version is still behind. Should be a simple case of removing the profile export once the apt version is back up to date

```sh
VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
DESTINATION=/usr/local/bin/docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
sudo chmod 755 $DESTINATION
echo "export DOCKER_COMPOSE_COMMAND=\"$DESTINATION\"" >> ~/.profile
```

**Comment by hassanas** [comment]
Any update here? how I can properly fix my project from last two days its not working ?

**Comment by mattijv** [comment]
@hassanas There are multiple workarounds in the thread. It's not an issue in Warden, but in `docker compose`.

Until there's an official release of the fixed `docker compose` version for your platform/installation method of choice, any of the workarounds should suffice.

**Comment by mattijv** [comment]
Just confirming that the latest Ubuntu release of `docker-compose-plugin` (`2.24.5-1~ubuntu.22.04~jammy`) has fixed this issue for me.

**Comment by hassanas** [comment]
Yes issue resolved on updating to new version:-
`hassan@hassan-Creator-15-A10SFS:~/Vamio/project_alrajhi-marketplace-m2$ docker compose version
Docker Compose version v2.24.2
hassan@hassan-Creator-15-A10SFS:~/Vamio/project_alrajhi-marketplace-m2$ docker compose version
Docker Compose version v2.24.5
`
please close this issue.

**Comment by dazimax** [comment]
As I noticed, the `nginx.base.yml` file already defines the `nginx` service and that service already defined in the `varnish.base.yml` file as well. Hence, when `warden env up` validation failed.

`nginx.base.yml`

```
services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: ${WARDEN_IMAGE_REPOSITORY}/nginx:${NGINX_VERSION:-1.16}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=2
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:cached
    environment:
      - XDEBUG_CONNECT_BACK_HOST=${XDEBUG_CONNECT_BACK_HOST:-''}

```

`varnish.base.yml`

```
services:
  nginx:
    labels:
      - traefik.enable=false
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=2
      - traefik.docker.network=${WARDEN_ENV_NAME}_default

  varnish:
    hostname: "${WARDEN_ENV_NAME}-varnish"
    image: ${WARDEN_IMAGE_REPOSITORY}/varnish:${VARNISH_VERSION:-6.0}
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-varnish.loadbalancer.server.port=80
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
```

**How to fix it?**
- I just removed the `nginx` service section from the `varnish.base.yml` file, and it worked as expected since no duplicated `nginx` services were found when running the `warden env up` command.

`updated varnish.base.yml`

```
services:
  varnish:
    hostname: "${WARDEN_ENV_NAME}-varnish"
    image: ${WARDEN_IMAGE_REPOSITORY}/varnish:${VARNISH_VERSION:-6.0}
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-varnish.loadbalancer.server.port=80
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
```
