### ISSUE TITLE
[Image] Varnish and Nginx services have duplicate labels (causing issues with latest docker compose)

### ISSUE THREAD

**Issue by mattijv** [wardenenv/warden#740]
### Version of Warden

0.14.2

### Operating System and Installation Method

Ubuntu 22.04.3 LTS via brew

### Image

The issue is with these partials
/home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/nginx.base.yml
/home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/varnish.base.yml

### Describe the Bug

Running `warden env up` (or pretty much any Warden command which results in the above-mentioned partials to be included) results in the follow error:

```
validating /home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/varnish.base.yml: services.nginx.labels array items[2,7] must be unique
```

### To Reproduce

1. Update Docker to 25.0.0 and `docker-compose` to  2.24.1
2. Go to a Warden project.
3. `warden env up`

### Expected Behavior

Environment starts up.

### Additional context

I recently updated to Warden 0.14.2, but looks like neither service definition has changed in three years, so I don't imagine it's the Warden update that caused this. I also (I think at the same time) updated Docker/`docker compose` to the latest version, which I think is what surfaced this issue.

```
dpkg -l | grep docker # + some formatting stuff
docker-buildx-plugin      0.12.1-1~ubuntu.22.04~jammy
docker-ce                 5:25.0.0-1~ubuntu.22.04~jammy
docker-ce-cli             5:25.0.0-1~ubuntu.22.04~jammy
docker-ce-rootless-extras 5:25.0.0-1~ubuntu.22.04~jammy
docker-compose-plugin     2.24.1-1~ubuntu.22.04~jammy
```

If I remove the last two labels in `/home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/varnish.base.yml`, everything works as expected.

I do have some custom partials included in environments, but I made sure the error also happens when just the default definitions are included by Warden.

A simple test case to replicate the issue:

```
#a.yml
version: "3.5"
services:
  nginx:
    image: docker.io/wardenenv/nginx:1.16
    labels:
      - foo=bar

#b.yml
version: "3.5"
services:
  nginx:
    labels:
      - foo=bar

docker compose -f a.yml -f b.yml up --dry-run
```
