### ISSUE TITLE
xdebug 3 not working for php8.3

### ISSUE THREAD

**Issue by hassan-vaimo** [wardenenv/warden#848]
### Version of Warden

0.14.1

### Operating System and Installation Method

Ubuntu 24.04.2 LTS via Brew

### Describe the Bug

Following error occurred on command `bin/magento`
in debug mode `warden bebug`
```
www-data@marketplace-upgrade-php-debug:/var/www/html$ bin/magento 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (fallback through xdebug.client_host/xdebug.client_port).
```

**Comment by hassan-vaimo** [comment]
No idea why its trying to connect on 172.19.0.1 this need to address.
But I resolved this issue by adding `XDEBUG_CONFIG: "client_host=host.docker.internal"` in warden-env.yml file

 ```
 php-debug:
    environment:
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
```
