### ISSUE TITLE
Issue: Xdebug Fails with warden env build and Custom Dockerfile

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#868]
### Version of Warden

0.15.0

### Operating System and Installation Method

MacOs Sonoma via brew

### Describe the Bug

If you create a custom `Dockerfile` where you install some PHP extension, XDebug is not working.

### To Reproduce

1. Create a Docker file
```
FROM docker.io/wardenenv/php-fpm:8.2-magento2
USER root

RUN set -eux \
    && yum install epel-release -y \
    && yum install dnf -y \
    && dnf install -y php-pecl-mongodb \
    && dnf clean all \
    && rm -rf /var/cache/dnf

USER www-data
```

And warden env file: `.warden/warden-env.yml` with content:
```
services:
  php-fpm:
    build:
      context: ./.warden/php
  php-debug:
    build:
      context: ./.warden/php
```

2. `warden env build`
3. `warden env up`
4. Log in to the debug shell and check for Xdebug using `php -m | grep debug`. You'll notice it returns no results, and Xdebug breakpoints are not working at all.

### Expected Behavior

After building with the custom `Dockerfile`, Xdebug should remain unaffected and continue to work as expected.
